### ISSUE TITLE
Issues setting it up

### ISSUE THREAD

**Issue by chrpayne2001** [simontelephonics/freepbx-telnyx-sms#2]
Hi, im running into some problems with the setup, it does not seem to be receiving nor sending texts but in the logs I see it runs the dialplan change.

I was wondering if it would be possible to maybe get on a call to go through it? I will gladly pay for your time.

Thanks, didnt really know where else I can post this.

**Comment by billsimon** [comment]
The scripts should log some results to /tmp/sms.log - are you seeing anything there?

**Comment by chrpayne2001** [comment]
I dont seem to even have an sms.log file there, I have cron.error, hsperfdata_root, reader.log, etc...

**Comment by chrpayne2001** [comment]
For example, here is what the Asterisk Log File gives me:

51736	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:1] NoOp("Message/ast_msg_queue", "Sending SMS to 6132825179 from "100" <sip:100@10.0.1.50>") in new stack	
51737	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:2] Set("Message/ast_msg_queue", "FROMUSER=sip:100@10.0.1.50>") in new stack	
51738	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:3] Set("Message/ast_msg_queue", "FROMUSER=sip:100") in new stack	
51739	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:4] Set("Message/ast_msg_queue", "FROMUSER=100") in new stack	
51740	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:5] Set("Message/ast_msg_queue", "CALLERID(num)=100") in new stack	
51741	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:6] Set("Message/ast_msg_queue", "SMSCID=13436334776") in new stack	
51742	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:7] ExecIf("Message/ast_msg_queue", "0?Goto(messages-out,nocid,1):Set(FROM=13436334776)") in new stack	
51743	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:8] NoOp("Message/ast_msg_queue", "Using external caller ID of 13436334776") in new stack	
51744	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:9] Set("Message/ast_msg_queue", "CURLOPT(conntimeout)=4") in new stack	
51745	[2021-07-18 18:30:36] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:10] Set("Message/ast_msg_queue", "CURLOPT(httptimeout)=4") in new stack	
51746	[2021-07-18 18:30:37] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:11] NoOp("Message/ast_msg_queue", "") in new stack	
51747	[2021-07-18 18:30:37] VERBOSE[2482][C-000000cf] pbx.c: Executing [6132825179@messages-out:12] Hangup("Message/ast_msg_queue", "") in new stack	
51748	[2021-07-18 18:30:37] VERBOSE[2482][C-000000cf] pbx.c: Spawn extension (messages-out, 6132825179, 12) exited non-zero on 'Message/ast_msg_queue'

**Comment by billsimon** [comment]
Must not be executing the script. Check that the path is right in https://github.com/simontelephonics/freepbx-telnyx-sms/blob/main/dialplan/extensions_custom.conf#L36 And look at your web server logs to see whether there's an error.

**Comment by chrpayne2001** [comment]
Does the sms folder with those php files have to be on the same web server as freepbx?

**Comment by chrpayne2001** [comment]
Seems like receiving texts doesnt work either.. Each time I send a text from my cell to a telnyx number, it says 54613	[2021-07-18 19:38:43] VERBOSE[2479] asterisk.c: Remote UNIX connection	
54614	[2021-07-18 19:38:43] VERBOSE[11680] asterisk.c: Remote UNIX connection disconnected

**Comment by billsimon** [comment]
Please send me your contact info through my contact form at https://simon.tel/contact/ with your availability and I'll set up some time with you to troubleshoot.
